ALTER TABLE sync_runs ADD COLUMN IF NOT EXISTS actor_type TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE sync_runs ADD COLUMN IF NOT EXISTS actor_name TEXT NOT NULL DEFAULT '';
ALTER TABLE sync_runs ADD COLUMN IF NOT EXISTS transport TEXT NOT NULL DEFAULT 'unknown';
